<?php
// This class was automatically generated by build task
<<<<<<< HEAD
// You can change it manually, but it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Maybe;
=======
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile


use \Codeception\Maybe;
>>>>>>> yii/master
use Codeception\Module\CodeHelper;

/**
 * Inherited methods
<<<<<<< HEAD
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void amTesting($method)
 * @method void amTestingMethod($method)
 * @method void testMethod($signature)
=======
 * @method void execute($callable)
 * @method void wantToTest($text)
 * @method void wantTo($text)
>>>>>>> yii/master
 * @method void expectTo($prediction)
 * @method void expect($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
<<<<<<< HEAD
 * @method void lookForwardTo($role)
=======
 * @method void lookForwardTo($achieveValue)
 * @method void offsetGet($offset)
 * @method void offsetSet($offset, $value)
 * @method void offsetExists($offset)
 * @method void offsetUnset($offset)
>>>>>>> yii/master
*/

class CodeGuy extends \Codeception\AbstractGuy
{
    
}

